### ISSUE TITLE
VB Script Language Support?

### ISSUE THREAD

**Issue by kleerkoat** [arcticicestudio/nord-atom-syntax#32]
could it or is it implemented? please. thank you.

**Comment by arcticicestudio** [comment]
VB syntax highlighting should be working fine out of the box.
I've tested it and everything is colored correct.

But in order to enable VB for Atom you need to install the specific package. Atom supports many languages out of the box (core language packages), but VB must be installed as community package.
I used the community package [`language-vb`](https://atom.io/packages/language-vb) created and maintained by  [Gorea235](https://github.com/Gorea235).

If you're already using this package but would like to change parts of the syntax highlighting or found missing, non-colored elements you can post these suggestions here and I'll see if it fits the overall theme style.

**Comment by kleerkoat** [comment]
i should have looked at  vanilla vbscript file, my apologies. a 3d program i use has their own flavor and i only have seen their flavor rendered. sorry.

**Comment by arcticicestudio** [comment]
No problem 😄 
You can try to set the language for the file manually to VB to see if it also works for the specific flavor, Atom detects file by their extension which may be the reason the file has been colored as "Plain Text" because no package is linked to the file extension.
If you're familar with JavaScript/Coffeescript you could also fork the `language-vb` package and create a new one for this 3D tool flavor or maybe create a issue in the repository so the creator may add the file extension to the package 😃
