### ISSUE TITLE
Reference highlighting in markdown

### ISSUE THREAD

**Issue by eldre** [arcticicestudio/nord-atom-syntax#59]
Hi,

I am using Nord to highlight syntax when writing in Markdown, and I would like to highlight a reference inserted in the text (which is cited in a .bib BibTeX file).

<img width="881" alt="Capture d’écran 2019-04-15 à 16 37 01" src="https://user-images.githubusercontent.com/26228189/56163592-b6ec7f00-5f9c-11e9-9ce8-c8430bfa7283.png">

Typically, I expected `@Reference1` and `@Reference2` to be coloured so that I am able to spot them more easily.

Is it just a problem with my installation, or could this be a new feature implemented in the syntax style?

Thanks for you help!

**Comment by arcticicestudio** [comment]
Hi @eldre, sorry for the really late reply, there a hundreds of notifications/messages in my inbox and it looks like I've missed this one :astonished: 

It looks like this is no valid Markdown syntax. If you'd like to create a reference link the `@Reference1` token must be wrapped into square brackets `[]` immediately followed by the ID of the reference also wrapped into square brackets.
The actual reference target URL must be defined somewhere in the document, mostly these are placed at the bottom of the file:

```md
According to [@Reference1][@Reference2], this is something...
This is a [link without a reference](https://google.com).

[@Reference2]: https://github.com
```

Note that it's better to use lowercase names for reference link IDs.

For a detailed guide about the Markdown syntax check out the [free and open-source Markdown guide about _Links_][g].

If this doesn't solve your problem please feel free to response, otherwise you can simply close this issue :smile: 

[g]: https://www.markdownguide.org/basic-syntax/#links

**Comment by arcticicestudio** [comment]
@eldre Any update on this, have you been able to solve/fix the problem or is it still not being rendered correctly when using Nord with the correct Markdown syntax?

**Comment by eldre** [comment]
Hi @arcticicestudio,

I am sorry for this late reply, I had many ongoing projects that were impacted by the current COVID situation. Now that I have more time, I will be able to monitor this thread and continue the discussion!

Indeed, I have no highlighting problem when I use the syntax `[@Reference1](link)`. It works perfectly this way and I used this many times when I needed to add a link to my document.

However, I was referring to a specific type of highlight that detect citation tags, such as `@Reference1`, which refers to a certain entry in a complementary .bib file. When I knit my .Rmd document using pandoc, it replaces this tag by the linked citation, formatted using a .csl or .cls file. I saw that some Atom Style packages did have this specific highlighting, so I was wondering if it worked with Nord too!

Cheers,
eldre

**Comment by eldre** [comment]
To add to my previous comment, the specific highlighting I was referring to may be used to tag usernames when mentioned in the text. This is basically what I want to have when I add a citation in the text (such as `@Reference1`). A certain formatting will then be applied in the rendered document thanks to the CSL and BibTeX files.

Also, I noticed that `@Reference1` tags are correctly highlighted when I set the language of the document to "Github Markdown" (.gfm), but not when it is only "Markdown" (.md) ...

I am not very savvy concerning Atom packages, but I hope this clarifies the issue.

Cheers
